[workspace]
members = [
    "my-proc-macro",
    "my-proc-macro-test",
]

[patch.crates-io]
my-proc-macro = { path = "./my-proc-macro" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
