[workspace]
members = [
    "my-proc-macro",
    "my-os-test",
    "my-runtime-lib",
]

[patch.crates-io]
my-proc-macro = { path = "./my-proc-macro" }
my-runtime-lib = { path = "./my-runtime-lib" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
