[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink64.ld",
]

[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink32.ld",
]
